services:
  discoveryserver:
    build: ./discoveryserver
    ports:
      - "8761:8761"

  apigateway:
    build: ./apigateway
    ports:
      - "8088:8088"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
    depends_on:
      - discoveryserver

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mainservice:
    build: ./mainservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
      - discoveryserver
    environment:
      # DB
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka

      # App secrets (example)
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env

  iot-service:
    build: ./IOT_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
      - discoveryserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
    env_file:
      - .env

  chatbotbackend:
    build: ./chatbotbackend
    ports:
      - "8081:8081"
    depends_on:
      - discoveryserver
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    env_file:
      - .env

  vitalreports:
    build: ./vitalReports-AI
    ports:
      - "8083:8083"
    depends_on:
      - discoveryserver
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka



  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - discoveryserver
      - apigateway
      - mainservice
      - iot-service
      - chatbotbackend
      - vitalreports

  grafana:
    image: grafana/grafana:11.1.4
    ports:
      - "3001:3000"
    depends_on:
      - prometheus



