server:
  port: 8088

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: iot-service
          uri: lb://iot-service
          predicates:
            - Path=/api/iot/**
          filters:
            - StripPrefix=0

        - id: chatbotbackend
          uri: lb://chatbotbackend
          predicates:
            - Path=/api/bot/**
          filters:
            - StripPrefix=0

        - id: vitalreports
          uri: lb://vitalreports
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0

        - id: mainservice
          uri: lb://mainservice
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discoveryservernew.internal.mangobush-8de88b36.southeastasia.azurecontainerapps.io:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
